"""Generate driver/multihost.py MECHANICALLY from the frozen multi-host accounting module of the historical
production authorization (p5y_k1_sr_production_authorized_successor/driver/multihost.py), substituting ONLY the
PS1 campaign constants (each asserted to occur exactly once) from config/PS1_CONSTANTS.json. All validators, the
cap gate, record validation, shard gates and reconciliation are the frozen text."""
import json
from pathlib import Path

NS = Path(__file__).resolve().parents[1]
SRC = NS.parent / "p5y_k1_sr_production_authorized_successor/driver/multihost.py"


def build(c: dict) -> str:
    s = SRC.read_text()
    roles_old = s[s.index("ROLES = {\n"):s.index("\n}\n", s.index("ROLES = {\n")) + 3]
    roles_new = "ROLES = " + json.dumps(c["ROLES"], indent=4).replace("true", "True").replace("false", "False") + "\n"
    subs = [
        ("GLOBAL_CPU_CAP = 4500.0          # ONE global campaign cap, never per host\n",
         f"GLOBAL_CPU_CAP = {float(c['GLOBAL_CPU_CAP'])!r}          # ONE global PS1 campaign cap, never per host\n"),
        ("CUSUM_CPU_H = 206.086\n", f"CUSUM_CPU_H = {float(c['GOVERNED_OVERHEAD_CPU_H'])!r}   # PS1: governed operational overhead (name kept frozen)\n"),
        ("TOTAL_CELLS = 316\n", f"TOTAL_CELLS = {int(c['TOTAL_CELLS'])}\n"),
        ("TOTAL_SR_OBLIGATIONS = 8849\n", f"TOTAL_SR_OBLIGATIONS = {int(c['TOTAL_SR_OBLIGATIONS'])}\n"),
        ("PROTOCOL_BOUND_CPU_CAP = 4500.0     # the frozen protocol value; never recomputed\n",
         f"PROTOCOL_BOUND_CPU_CAP = {float(c['GLOBAL_CPU_CAP'])!r}     # the PS1 protocol value; never recomputed\n"),
        (roles_old, roles_new),
    ]
    for a, b in subs:
        assert s.count(a) == 1, (a[:60], s.count(a))
        s = s.replace(a, b)
    head = ('# GENERATED by code/make_multihost.py from the frozen historical multihost.py with ONLY the PS1 campaign\n'
            '# constants substituted (config/PS1_CONSTANTS.json). Do not edit.\n')
    return head + s


if __name__ == "__main__":
    c = json.loads((NS / "config/PS1_CONSTANTS.json").read_text())
    (NS / "driver/multihost.py").write_text(build(c))
    print("generated driver/multihost.py")
