#!/usr/bin/env python3
"""Run and verify the deterministic generated-artifact pipeline."""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

from config import BASE, ROOT

PY = ROOT / "level4/.venv/bin/python"
GENERATED = [
    "results/gates.json",
    "results/task_household_confirmatory.json",
    "results/task_metro_confirmatory.json",
    "results/task_beijing_confirmatory.json",
    "results/task_household_analysis.json",
    "results/task_metro_analysis.json",
    "results/task_beijing_analysis.json",
    "results/decision.json",
    "results/summary.json",
    "CALIBRATION_AUDIT.md",
    "ADVERSARIAL_AUDIT.md",
    "RESULTS.md",
    "FINAL_REPORT.md",
    "figures/figure_a_reference_distortion.png",
    "figures/figure_b_normalized_response.png",
    "figures/figure_c_delay_alert_burden.png",
    "figures/figure_d_task_support.png",
]


def digest() -> str:
    value = hashlib.sha256()
    for relative in GENERATED:
        path = BASE / relative
        name = relative.encode()
        data = path.read_bytes()
        value.update(len(name).to_bytes(8, "big")); value.update(name)
        value.update(len(data).to_bytes(8, "big")); value.update(data)
    return value.hexdigest()


def run_pipeline():
    commands = [
        [PY, BASE / "src/gate.py"],
        [PY, BASE / "src/confirmatory.py"],
        [PY, BASE / "src/analyze.py"],
        [PY, BASE / "src/decision.py"],
        [PY, BASE / "src/summarize.py"],
        [PY, BASE / "src/figures.py"],
        [PY, BASE / "src/reports.py"],
    ]
    for command in commands:
        subprocess.run([str(part) for part in command], cwd=ROOT, check=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--establish", action="store_true")
    parser.add_argument("--check-run", action="store_true")
    parser.add_argument("--check-record", action="store_true")
    args = parser.parse_args()
    if args.check_record:
        record = json.loads((BASE / "results/reproduction.json").read_text())
        actual = digest()
        passed = record.get("status") == "PASS" and record.get("digest") == actual
        print(f"reproduction record: {'PASS' if passed else 'FAIL'} {actual}")
        return 0 if passed else 1
    before = digest()
    run_pipeline()
    after = digest()
    stable = before == after
    if args.establish:
        record = {
            "schema": "rebaseguard.external-validation-v2.reproduction.v1",
            "status": "PASS" if stable else "FAIL", "byte_stable": stable,
            "artifacts": len(GENERATED), "digest": after,
            "protocol_hash": json.loads((BASE / "results/protocol_hash.json").read_text())["combined_sha256"],
            "outcome_checkpoint": "00ee0f3a7d16a5ab7453899eda63d8426d272cd2",
        }
        (BASE / "results/reproduction.json").write_text(
            json.dumps(record, indent=2, sort_keys=True) + "\n")
    print(f"generated bytes: {'PASS' if stable else 'FAIL'} {after}")
    return 0 if stable else 1


if __name__ == "__main__":
    raise SystemExit(main())
