"""Render the human-readable stability-map report from the final JSON."""

from __future__ import annotations

from typing import Any

from .common import read_json
from .config import CAMPAIGN, M_GRID, RESULTS, RHO_GRID

REPORT = CAMPAIGN / "STABILITY_MAP_REPORT.md"


def _fmt(value: float | None, digits: int = 6) -> str:
    return "n/a" if value is None else f"{value:.{digits}f}"


def _gain_table(payload: dict[str, Any]) -> list[str]:
    lines = [
        "| detector | m | GammaTilde | exact | SE | 95% interval | gain evidence | provenance |",
        "|---|---:|---:|---|---:|---|---|---|",
    ]
    for row in payload["boundary_rows"]:
        ci = row["gamma_tilde_ci95"]
        lines.append(
            f"| {row['detector_short']} | {row['m']} | {row['gamma_tilde']:.6f} | "
            f"{row['gamma_tilde_exact'] or '--'} | "
            f"{_fmt(row['gamma_tilde_se'])} | "
            f"{'[%.6f, %.6f]' % tuple(ci) if ci else '--'} | "
            f"{row['gamma_evidence_class']} | {row['provenance_kind']} |"
        )
    return lines


def _boundary_table(payload: dict[str, Any]) -> list[str]:
    lines = [
        "| detector | m | regime | rho_crit | exact | delta SE | 95% interval "
        "| in [0,1] | admissible reading |",
        "|---|---:|---|---:|---|---:|---|---|---|",
    ]
    for row in payload["boundary_rows"]:
        ci = row["rho_crit_interval"]
        ci_text = "--"
        if ci and ci[0] is not None and ci[1] is not None:
            ci_text = f"[{ci[0]:.6f}, {ci[1]:.6f}]"
        elif ci:
            ci_text = "unbounded"
        lines.append(
            f"| {row['detector_short']} | {row['m']} | {row['gamma_regime']} | "
            f"{_fmt(row['rho_crit'])} | {row['rho_crit_exact'] or '--'} | "
            f"{_fmt(row['rho_crit_se_delta'])} | {ci_text} | "
            f"{'yes' if row['accessible_in_admissible_domain'] else 'no'} | "
            f"{row['admissible_interpretation']} |"
        )
    return lines


def _transition_table(payload: dict[str, Any]) -> list[str]:
    lines = [
        "| detector | m | last attracting grid rho | first repelling grid rho "
        "| grid cells not reportable as robust |",
        "|---|---:|---:|---:|---|",
    ]
    for layer in payload["layers"]:
        for m in M_GRID:
            cells = sorted(
                (c for c in payload["cells"]
                 if c["layer"] == layer["id"] and c["m"] == m),
                key=lambda c: c["rho"],
            )
            attracting = [c["rho"] for c in cells if c["class"] == "LOCALLY-STABLE"]
            repelling = [c["rho"] for c in cells if c["class"] == "LOCALLY-UNSTABLE"]
            fragile = [f"{c['rho']:g}" for c in cells
                       if not c["classification_reportable_as_robust"]]
            lines.append(
                f"| {layer['detector_short']} | {m} | "
                f"{max(attracting) if attracting else float('nan'):g} | "
                f"{min(repelling) if repelling else float('nan'):g} | "
                f"{', '.join(fragile) if fragile else 'none'} |"
            )
    return lines


def _comparison_table(payload: dict[str, Any]) -> list[str]:
    comparison = payload["cross_detector_comparison"]
    lines = [
        "| m | SR rho_c | SR 95% | CUSUM rho_c | CUSUM 95% | SR below CUSUM | intervals disjoint |",
        "|---:|---:|---|---:|---|---|---|",
    ]
    for row in comparison["windows"]:
        lines.append(
            f"| {row['m']} | {row['sr_rho_crit']:.6f} | "
            f"[{row['sr_rho_crit_ci95'][0]:.6f}, {row['sr_rho_crit_ci95'][1]:.6f}] | "
            f"{row['cusum_rho_crit']:.6f} | "
            f"[{row['cusum_rho_crit_ci95'][0]:.6f}, {row['cusum_rho_crit_ci95'][1]:.6f}] | "
            f"{'yes' if row['sr_boundary_below_cusum'] else 'no'} | "
            f"{'yes' if row['intervals_disjoint'] else 'no'} |"
        )
    return lines


def build() -> str:
    payload = read_json(RESULTS / "stability_map.json")
    figures = read_json(CAMPAIGN / "figures" / "figure_index.json")
    certificate = read_json(CAMPAIGN / "arb" / "certificate.json")

    lines = [
        "# Priority-3 cross-detector m-rho stability map",
        "",
        "This file is generated by `scripts/make_reports.py` from",
        "`results/stability_map.json`. Do not edit it by hand.",
        "",
        f"Protocol sha256: `{payload['protocol_sha256']}`",
        "",
        "## Imported identity",
        "",
        "```text",
        payload["derivative_identity"],
        "```",
        "",
        f"Classification rule: `{payload['classification_rule']}`.",
        f"Admissible reuse domain: `{payload['admissible_rho_domain']['interval']}`.",
        "",
        "## Gain provenance",
        "",
        *_gain_table(payload),
        "",
        "## Boundary table",
        "",
        *_boundary_table(payload),
        "",
        "## Grid transitions",
        "",
        f"Candidate-declared fixed reuse grid: `{RHO_GRID}`. Its temporal "
        "preregistration cannot be independently authenticated because the "
        "candidate arrived as one uncommitted intake.",
        "",
        *_transition_table(payload),
        "",
        "## Cross-detector comparison (empirical layers only)",
        "",
        *_comparison_table(payload),
        "",
        payload["cross_detector_comparison"]["scope"],
        "",
        "## Rigorous interval certification",
        "",
        f"Backend `{certificate['backend']}` at "
        f"{certificate['precision_bits']} bits. All checks pass: "
        f"`{certificate['all_checks_pass']}`. Gaussian layers certified: "
        f"`{certificate['gaussian_layers_certified']}`.",
        "",
        "## Figures",
        "",
        *[f"- `{name}` sha256 `{digest}`"
          for name, digest in sorted(figures["figures"].items())],
        "",
        f"Every plotted cell traceable: "
        f"`{figures['traceability']['every_plotted_cell_traceable']}` over "
        f"{figures['traceability']['checked_cells']} machine-readable cells.",
        "",
        "## Scope",
        "",
        payload["claim_scope"],
        "",
        payload["evidence_boundary"],
        "",
    ]
    text = "\n".join(lines)
    REPORT.write_text(text)
    return text
