#!/usr/bin/env bash
# Offline reproduction of the persisted novelty-verification decision.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
BASE="$ROOT/level4/closure_proofs/novelty_verification"
PY="$ROOT/level4/.venv/bin/python"

cd "$ROOT"

if [ ! -x "$PY" ]; then
  echo "missing interpreter: $PY" >&2
  exit 1
fi

echo "== frozen inputs and generated bytes =="
"$PY" "$BASE/src/generate_artifacts.py" --check

echo
echo "== focused novelty-verification tests =="
"$PY" -m pytest "$BASE/tests" -q

echo
echo "== final adversarial audit (read-only) =="
"$PY" "$BASE/src/run_adversarial.py" --check

echo
echo "== authoritative repository verification =="
bash "$ROOT/scripts/verify_level_4.sh"

echo
echo "== post-run byte-stability check =="
"$PY" "$BASE/src/generate_artifacts.py" --check

echo
echo "NOVELTY VERIFICATION REPRODUCTION OK"
