"""Generate succ_t4.py and succ_t5.py MECHANICALLY from the frozen t4_cell.t4 and t5_obligations.obligations sources.

Each generated function is the frozen function body with exactly the listed substitutions (each asserted to occur
exactly once): the cell record is passed in explicitly, geometry/identity/candidates come from the successor layer,
and T5's unit-structure check compares against the frozen per-cell unit structure of the PARENT cell. Every other
line - the ErrorDAG, sr_refine, assembly, ledger and all gates - is the frozen text. Re-running this script must
reproduce the committed files byte for byte (tests/test_successor.py).
"""
import ast
from pathlib import Path

NS = Path(__file__).resolve().parents[1]
CP = NS.parent
SRC4 = CP / "p5y_k1_sr_o9_t345_successor/code/t4_cell.py"
SRC5 = CP / "p5y_k1_sr_o9_t345_successor/code/t5_obligations.py"

SUB4 = [
    ("def t4(t3: dict, *, crude_only=False) -> dict:", "def t4(t3: dict, rec: dict, *, crude_only=False) -> dict:"),
    ('    cell_index = t3["cell"]\n', '    cell_index = rec["index"]\n'),
    ("    cell = T.frozen_cell(cell_index)\n", "    cell = SC.validate(rec)\n"),
    ('    built = T.build_cell_candidates(cell_index)["scientific"]\n', '    built = S1.build(rec)["scientific"]\n'),
    ("        g = T.cell_geometry(cell)\n", "        g = SC.geometry(cell)\n"),
]
SUB5 = [
    ("def obligations(t3: dict, t4: dict, evidence: dict) -> dict:", "def obligations(t3: dict, t4: dict, evidence: dict, rec: dict) -> dict:"),
    ('    C = Fr(T.frozen_cell(cell)["C_upper"])\n', '    C = Fr(SC.validate(rec)["C_upper"])\n'),
    ("    units = cell_units(cell)\n", '    units = cell_units(rec["id"])\n'),
    ('    frozen_ids = [u for u in universe.work_ids(cells=[T.frozen_cell(cell)]) if u[2] != "far_field"]\n',
     '    frozen_ids = [(u[0], rec["id"], u[2], u[3]) for u in universe.work_ids(cells=[T.frozen_cell(rec["parent_index"])])\n'
     '                  if u[2] != "far_field"]\n'),
]


def extract(src: Path, name: str) -> str:
    text = src.read_text()
    tree = ast.parse(text)
    fn = next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == name)
    lines = text.splitlines(keepends=True)
    return "".join(lines[fn.lineno - 1:fn.end_lineno])


def substitute(body: str, subs) -> str:
    for old, new in subs:
        assert body.count(old) == 1, (old, body.count(old))
        body = body.replace(old, new)
    return body


def build():
    h4 = ('"""GENERATED by make_successor_stages.py from the frozen t4_cell.t4 (see that script for the exact substitutions).\n'
          'Successor T4 for one successor cell; all algebra is the frozen text."""\n'
          "from t4_cell import *                                   # noqa: F401,F403  frozen helpers and modules\n"
          "import succ_cells as SC\nimport succ_t1 as S1\n\n\n")
    h5 = ('"""GENERATED by make_successor_stages.py from the frozen t5_obligations.obligations (see that script for the exact\n'
          'substitutions). Successor T5 for one successor cell; all gates are the frozen text."""\n'
          "from t5_obligations import *                            # noqa: F401,F403  frozen helpers and modules\n"
          "from t5_obligations import _fin                         # noqa: F401\n"
          "import succ_cells as SC\n\n\n")
    return (h4 + substitute(extract(SRC4, "t4"), SUB4), h5 + substitute(extract(SRC5, "obligations"), SUB5))


def main():
    a, b = build()
    (NS / "code/succ_t4.py").write_text(a)
    (NS / "code/succ_t5.py").write_text(b)
    print("generated", len(a), len(b))


if __name__ == "__main__":
    main()
