"""GENERATED by make_successor_stages.py from the frozen t4_cell.t4 (see that script for the exact substitutions).
Successor T4 for one successor cell; all algebra is the frozen text."""
from t4_cell import *                                   # noqa: F401,F403  frozen helpers and modules
import succ_cells as SC
import succ_t1 as S1


def t4(t3: dict, rec: dict, *, crude_only=False) -> dict:
    cell_index = rec["index"]
    cell = SC.validate(rec)
    built = S1.build(rec)["scientific"]
    mant = {x["node"]: x["mantissas"] for x in built["candidates"]}
    hashes = {x["node"]: x["identity_hash"] for x in built["candidates"]}
    if hashlib.sha256(T.canonical(sorted(hashes.items()))).hexdigest() not in t3["candidate_identity_list_sha256"]:
        raise T.T1Refusal("T3 record was produced from a different candidate set")
    struct = op_structure()
    C = Fr(cell["C_upper"])
    terminal = Fr(cell["rho"][1]) != 0
    with T.scientific_precision():
        g = SC.geometry(cell)
        e0, rho = g["e0"], g["rho"]
        e_cell = e0 + arb(0, rho.abs_upper())
        rho_x = rho if terminal else exact(Fr(cell["rho"][0]))
        n_mid, n_cell = norms_at(e0), norms_at(e_cell)
        mid = build_dag("mid", t3, C, n_mid, struct)
        cel = build_dag("cell", t3, C, n_cell, struct)
        refined, trails = {}, {}
        for r in range(5):
            inp = sr_refine.RefinementInputs(
                rho=rho_x, C=exact(C), k1=n_cell["k"][1], k2=n_cell["k"][2], e_abs=arb(e_cell.abs_upper()),
                eps_F_mid=mid.get(f"F:{r}:k0"), eps_D_mid=mid.get(f"F:{r}:k1"),
                eps_F_crude=cel.get(f"F:{r}:k0"), eps_D_crude=cel.get(f"F:{r}:k1"), eps_H_crude=cel.get(f"F:{r}:k2"),
                delta_H_cell=exact(Fr(t3["delta"]["cell"][f"F:{r}:k2"]["delta"])),
                eps_S2_cell=cel.get(f"Ssrc:{r}:k2"),
                sup_D_hat=cand_sup(mant[f"F:{r}:k1"]), sup_H_hat=cand_sup(mant[f"F:{r}:k2"]),
                eps_h1_d1=arb(0), eps_h1_d2=arb(0))
            res = sr_refine.refine_cell(inp, enabled=not crude_only)
            refined[r] = res
            trail = []
            if not crude_only:
                for it in range(1, res.iterations + 1):
                    x = sr_refine.refine_cell(inp, iterations=it)
                    trail.append({"iteration": it, "eps_F_cell": str(mag_fraction(x.eps_F_cell)),
                                  "eps_D_cell": str(mag_fraction(x.eps_D_cell)), "eps_H_cell": str(mag_fraction(x.eps_H_cell)),
                                  "sup_H": str(mag_fraction(x.sup_H))})
            trails[r] = {"summary": res.as_dict(), "sequence": trail,
                         "inputs": {k: str(mag_fraction(getattr(inp, k))) for k in (
                             "rho", "C", "k1", "k2", "e_abs", "eps_F_mid", "eps_D_mid", "eps_F_crude", "eps_D_crude",
                             "eps_H_crude", "delta_H_cell", "eps_S2_cell", "sup_D_hat", "sup_H_hat", "eps_h1_d1", "eps_h1_d2")}}
        x0i = t3["x0_images"]

        def value(node, mode):
            return cand_x0(mant[node]) if node in mant else img_x0(x0i[mode][node])
        enc = {"F": {r: assembly.enclose(value(f"F:{r}:k0", "mid"), mid.get(f"F:{r}:k0")) for r in range(5)},
               "D": {r: assembly.enclose(value(f"F:{r}:k1", "mid"), mid.get(f"F:{r}:k1")) for r in range(5)},
               "H": {r: assembly.enclose(value(f"F:{r}:k2", "mid"), refined[r].eps_H_cell) for r in range(5)},
               "H_crude": {r: assembly.enclose(value(f"F:{r}:k2", "mid"), cel.get(f"F:{r}:k2")) for r in range(5)},
               "W": {}}
        for k, dag, mode in ((0, mid, "mid"), (1, mid, "mid"), (2, cel, "cell")):
            enc["W"][k] = {(r, j): assembly.enclose(value(wnode(r, j, k), mode), dag.get(wnode(r, j, k)))
                           for r in range(4) for j in range(0, 4 - r)}
        per_m = {}
        chmax = {q: {r: Fr(t3["delta"]["mid"][f"F:{r}:k0"]["channels_max"][q]["value"]) for r in range(5)}
                 for q in ("eq", "trunc", "tail", "end", "int", "round")}
        for m in spec.M_VALUES:
            R_int = assembly.assemble(m, enc["F"], enc["W"][0])
            D_int = assembly.assemble(m, enc["D"], enc["W"][1])
            R2_int = assembly.assemble(m, enc["H"], enc["W"][2])
            R2_crude = assembly.assemble(m, enc["H_crude"], enc["W"][2])
            M_R2 = assembly.curvature_bound(R2_int)
            u_cand = sum(C * Fr(t3["delta"]["mid"][f"F:{r}:k0"]["delta"]) / m for r in range(m))
            channels = {q: sum(C * chmax[q][r] / m for r in range(m)) for q in chmax}
            u_kernel = sum(C * mag_fraction(mid.get(f"Ssrc:{r}:k0")) / m for r in range(m))
            for t in range(1, m):
                for r in range(t):
                    u_kernel += (Fr(1, t) - Fr(1, m)) * mag_fraction(mid.get(wnode(r, t - r - 1, 0)))
            eta_i = mag_fraction(assembly.assembly_arithmetic_excess(m, enc["F"], enc["W"][0], R_int))
            usage = {"B_candidate": u_cand, "B_kernel": u_kernel, "B_interval": eta_i, "B_rounding": Fr(0), "B_other": Fr(0)}
            if terminal:
                led = arb_rho_ledger(m=m, cell=cell, rho=rho, R_interval=R_int, D_interval=D_int, M_R2=M_R2,
                                     usage=usage, candidate_channels=channels)
            else:
                led = ledger.cell_ledger(m=m, cell=cell, R_interval=R_int, D_interval=D_int, M_R2=M_R2,
                                         usage=usage, candidate_channels=channels)
            rho_u = arb(rho_x.abs_upper())
            crude_cover = rho_u * D_int.abs_upper() + rho_u * rho_u * assembly.curvature_bound(R2_crude) / arb(2)
            led.update({"R_interval": record(R_int), "D_interval": record(D_int), "R2_interval": record(R2_int),
                        "R2_interval_unrefined": record(R2_crude),
                        "W_cover_unrefined_upper": str(mag_fraction(crude_cover)),
                        "B_cover_ratio": float(Fr(led["cover"]["usage"]) / spec.TOP_BUDGETS["B_cover"]),
                        "channel_provenance": {"B_rounding": "0: candidate values at x0 are exact dyadics; image values "
                                                            "at x0 are outward Arb balls (rounding inside the ball)",
                                               "nested_channels": "sum_(r<m) C * max_patch(channel q of F_r at e0) / m"}})
            per_m[m] = led
    out = {"schema": "rebaseguard.p5y.k1.sr.o9.t4-cell.v1", "cell": cell_index, "terminal_cell": terminal,
           "t3_record_sha256": t3["t3_record_sha256"], "C_upper": cell["C_upper"], "e0": cell["e0"], "rho": cell["rho"],
           "rho_upper": str(mag_fraction(rho_x)),
           "norms": {"mid": {k: [str(mag_fraction(x)) for x in v] for k, v in n_mid.items()},
                     "cell": {k: [str(mag_fraction(x)) for x in v] for k, v in n_cell.items()}},
           "dag_audit": {"mid": mid.audit(), "cell": cel.audit()},
           "eps_mid": {k: str(mag_fraction(v)) for k, v in sorted(mid.nodes.items())},
           "eps_cell": {k: str(mag_fraction(v)) for k, v in sorted(cel.nodes.items())},
           "refinement": {str(r): v for r, v in trails.items()},
           "x0_enclosures": {"F": {r: record(v) for r, v in enc["F"].items()}, "D": {r: record(v) for r, v in enc["D"].items()},
                             "H": {r: record(v) for r, v in enc["H"].items()},
                             "W": {k: {f"{r},{j}": record(v) for (r, j), v in d.items()} for k, d in enc["W"].items()}},
           "local_gates_all_patches": t3["checks"]["all_F_local_gates_all_patches"],
           "m": {str(m): v for m, v in per_m.items()}}
    out["all_m_status"] = {str(m): v["status"] for m, v in per_m.items()}
    out["B_cover_ratio"] = {str(m): v["B_cover_ratio"] for m, v in per_m.items()}
    out["t4_record_sha256"] = hashlib.sha256(canonical(out)).hexdigest()
    return out
