"""GENERATED by make_successor_stages.py from the frozen t5_obligations.obligations (see that script for the exact
substitutions). Successor T5 for one successor cell; all gates are the frozen text."""
from t5_obligations import *                            # noqa: F401,F403  frozen helpers and modules
from t5_obligations import _fin                         # noqa: F401
import succ_cells as SC


def obligations(t3: dict, t4: dict, evidence: dict, rec: dict) -> dict:
    cell = t3["cell"]
    C = Fr(SC.validate(rec)["C_upper"])
    units = cell_units(rec["id"])
    # frozen universe.work_ids appends the two global far-field units after the per-cell units; they are not cell units
    frozen_ids = [(u[0], rec["id"], u[2], u[3]) for u in universe.work_ids(cells=[T.frozen_cell(rec["parent_index"])])
                  if u[2] != "far_field"]
    ids_ok = sorted(map(tuple, frozen_ids)) == sorted(units) and len(units) == 28
    t3ok = t3["T3_PASS"]
    dm, dc = t3["delta"]["mid"], t3["delta"]["cell"]
    em, ec = t4["eps_mid"], t4["eps_cell"]
    audits_ok = all(a["duplicate_edges"] == 0 and a["derivative_edges_all_cover"] for a in t4["dag_audit"].values())

    def node_gates(nodes):
        g = {"T3_complete_conforming_coverage": {"PASS": t3ok}}
        for n in nodes:
            g[f"residual_finite:{n}"] = {"PASS": _fin(dm[n]["delta"]) and _fin(dc[n]["delta"]),
                                          "delta_mid": dm[n]["delta_float"], "delta_cell": dc[n]["delta_float"]}
            g[f"eps_finite:{n}"] = {"PASS": _fin(em[n]) and _fin(ec[n]), "eps_mid": float(Fr(em[n])), "eps_cell": float(Fr(ec[n]))}
        g["dag_no_double_count"] = {"PASS": audits_ok}
        return g

    def obj_nodes(tag):
        if tag.startswith("h_"):
            return [f"h:{tag[2:]}:k0"]
        if tag.startswith("S_"):
            return [f"S:{tag[2:]}:k0"]
        if tag.startswith("dF_"):
            return [f"F:{tag[3:]}:k1"]
        return [f"F:{tag[2:]}:k0"]

    certs, out = {}, []
    for u in units:
        det, index, kind, tag = u
        deps = dependencies_of(u)
        dep_status = {uid(d): certs[uid(d)]["status"] for d in deps}
        if kind == "object":
            gates = node_gates(obj_nodes(tag))
            if tag.startswith("F_"):
                n = obj_nodes(tag)[0]
                chm = dm[n]["channels_max"]
                caps = {q: Fr(T.spec.NESTED_CANDIDATE[f"B_{q}"]) for q in ("eq", "trunc", "tail", "end", "int", "round")}
                gates["per_patch_nested_F_gates_and_endpoint_and_local_budget_all_3994"] = {
                    "PASS": t3["checks"]["all_F_local_gates_all_patches"]}
                worst = max(float(C * Fr(chm[q]["value"]) / caps[q]) for q in caps)
                gates["channel_max_over_patches_vs_nested_caps"] = {"PASS": worst <= 1, "worst_ratio": worst}
                margin = {"worst_nested_channel_ratio": worst}
            else:
                margin = {"eps_mid": gates[f"eps_finite:{obj_nodes(tag)[0]}"]["eps_mid"]}
            content = {n: {"delta_mid": dm[n]["delta"], "delta_cell": dc[n]["delta"], "eps_mid": em[n], "eps_cell": ec[n]}
                       for n in obj_nodes(tag)}
            governing = "object certificate (ERROR_ALGEBRA 1-2, 6)"
        elif kind == "dependency_bundle":
            nodes = ([f"h:{j}:k{k}" for j in range(1, 5) for k in (0, 1)] + [f"S:{r}:k{k}" for r in range(5) for k in (0, 1)]
                     + [f"W:{rj}:k{k}" for rj in ("0,1", "0,2", "0,3", "1,1", "1,2", "2,1") for k in (0, 1)])
            gates = node_gates(nodes)
            content = {n: {"eps_mid": em[n], "eps_cell": ec[n]} for n in nodes}
            margin = {"max_eps_mid": max(float(Fr(em[n])) for n in nodes)}
            governing = "order-0/1 source and finite-power bundle (ERROR_ALGEBRA 2)"
        elif kind == "curvature":
            led = t4["m"][tag]
            ref_ok = all(v["summary"]["refinement_enabled"] for v in t4["refinement"].values())
            gates = {"R2_from_cell_uniform_inputs": {"PASS": True, "evidence": "H: sr_refine eps_H_cell over cell-mode DAG; "
                                                                             "W'': cell-mode DAG and cell-mode image x0 values"},
                     "refinement_valid_no_loosening": {"PASS": ref_ok},
                     "M_R2_finite_nonnegative": {"PASS": _fin(led["M_R2"]), "M_R2": float(Fr(led["M_R2"]))},
                     "frozen_ledger_status_m": {"PASS": led["status"] == "PASS", "status": led["status"]}}
            content = {"R2_interval": led["R2_interval"], "M_R2": led["M_R2"]}
            margin = {"curvature_share_of_B_cover": float(Fr(led["cover"]["children"]["curvature"]) / Fr(1, 20))
                      if isinstance(led["cover"]["children"]["curvature"], str) else None}
            governing = "curvature obligation (ERROR_ALGEBRA 3) + frozen per-m ledger"
        else:
            led = t4["m"][tag]
            tg = led["top_level_gates"]
            gates = {f"top_level:{k}": {"PASS": v.get("status") == "PASS", "usage": v.get("usage"), "cap": v.get("cap"),
                                        "utilization": v.get("utilization")}
                     for k, v in tg.items() if k not in ("top_reserve", "total")}
            gates.update({f"nested:{k}": {"PASS": v.get("status") == "PASS", "usage": v.get("usage"), "cap": v.get("cap")}
                          for k, v in led["nested_candidate_gates"].items() if k != "B_reserve"})
            gates["target_strictly_inside_(-2,2)"] = {"PASS": led["target_gate"]["status"] == "PASS",
                                                      "lo": led["target_gate"]["lo"], "hi": led["target_gate"]["hi"]}
            gates["frozen_ledger_status_m"] = {"PASS": led["status"] == "PASS"}
            content = {"R_interval": led["R_interval"], "D_interval": led["D_interval"], "cover": led["cover"]}
            margin = {"B_cover_ratio": led["B_cover_ratio"],
                      "worst_top_level_utilization": max((v.get("utilization") or 0) for k, v in tg.items()
                                                         if k not in ("top_reserve", "total", "B_resolvent"))}
            governing = "assembly obligation: complete frozen STYLE_1 ledger (ERROR_ALGEBRA 4-7)"
        gates["dependencies_all_PASS"] = {"PASS": all(s == "PASS" for s in dep_status.values()), "dependencies": dep_status}
        status = "PASS" if all(g["PASS"] for g in gates.values()) else "FAIL"
        ident = {"obligation_id": uid(u), "detector": det, "cell_index": index, "unit_kind": kind, "function_or_m": tag,
                 "dependencies": [uid(d) for d in deps],
                 "source_certificate_hashes": {uid(d): certs[uid(d)]["certificate_hash"] for d in deps}}
        cert = {"identity": ident, "governing_frozen_gate": governing, "gates": gates, "certified": content,
                "margin": margin, "status": status, "evidence_sha256": evidence}
        cert["certificate_hash"] = hashlib.sha256(canonical({k: v for k, v in cert.items() if k != "certificate_hash"})).hexdigest()
        certs[uid(u)] = cert
        out.append(cert)
    # chain re-verification by recomputation
    chain_ok = True
    for c in out:
        h = hashlib.sha256(canonical({k: v for k, v in c.items() if k != "certificate_hash"})).hexdigest()
        chain_ok &= h == c["certificate_hash"]
        for d, dh in c["identity"]["source_certificate_hashes"].items():
            chain_ok &= certs[d]["certificate_hash"] == dh
    n_pass = sum(1 for c in out if c["status"] == "PASS")
    return {"schema": "rebaseguard.p5y.k1.sr.o9.t5-obligations.v1", "cell": cell, "obligation_ids_equal_frozen_universe": ids_ok,
            "provenance_chain_verified": chain_ok, "pass_count": n_pass, "total": len(out),
            "status": ("T5_28_OF_28_PASS" if n_pass == 28 and ids_ok and chain_ok else "T5_NOT_28_OF_28"),
            "obligations": out}
