#!/usr/bin/env python3
"""Rebuild the audit-only core twice and verify byte stability offline."""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess

from config import BASE, PY, ROOT


GENERATED = [
    "results/evidence_audit.json",
    "results/derived_decision.json",
    "REQUIREMENT_LEDGER.md",
    "EVIDENCE_MAP.md",
    "CLAIM_FIREWALL.md",
]


def digest() -> str:
    value = hashlib.sha256()
    for relative in GENERATED:
        path = BASE / relative
        name, data = relative.encode(), path.read_bytes()
        value.update(len(name).to_bytes(8, "big")); value.update(name)
        value.update(len(data).to_bytes(8, "big")); value.update(data)
    return value.hexdigest()


def generate() -> None:
    subprocess.run([str(PY), str(BASE / "src/audit.py")], cwd=ROOT, check=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--establish", action="store_true")
    parser.add_argument("--check-run", action="store_true")
    parser.add_argument("--check-record", action="store_true")
    args = parser.parse_args()
    record_path = BASE / "results/reproduction.json"
    if args.check_record:
        record = json.loads(record_path.read_text())
        actual = digest()
        passed = record.get("status") == "PASS" and record.get("digest") == actual
        print(f"final-audit reproduction record: {'PASS' if passed else 'FAIL'} {actual}")
        return 0 if passed else 1
    before = digest()
    generate()
    middle = digest()
    generate()
    after = digest()
    stable = before == middle == after
    if args.establish:
        record = {
            "schema": "rebaseguard.level4-final-global-reproduction.v1",
            "status": "PASS" if stable else "FAIL",
            "byte_stable": stable,
            "offline": True,
            "generated_artifacts": len(GENERATED),
            "digest": after,
            "audited_commit": "ba9f49d202b8feb71fb4923929b506f8e9b88a40",
        }
        record_path.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n")
    print(f"final-audit generated bytes: {'PASS' if stable else 'FAIL'} {after}")
    return 0 if stable else 1


if __name__ == "__main__":
    raise SystemExit(main())
