"""Cell-308 MB-S successor campaign (r1) -- re-pin tooling (non-holder builder5, research brief 50; the `apply` step by
the non-holder builder6, research brief 54, part B2). Target-free; NOT frozen. It never imports the driver (which would
load the science modules); it reads and rewrites TEXT only, imports nothing of the campaign but mbs308_host (for the
same host readings the driver uses) and, for `apply`, the pure derivation module mbs308_derive, and is DRY-RUN by
default: nothing is written without an explicit flag.

  helpers      recompute HELPER_SHA256 mechanically: the sha256 of each helper file named by the driver's table,
               compared with the pinned value; `--write` rewrites exactly the stale values of that table.
  platform     the PLATFORM_PINS the driver's platform_readings() would read on THIS host with THIS interpreter
               (realpath of sys.executable and its sha256, the pinned libpython path and its sha256, sys.version,
               `sw_vers -buildVersion`, `uname -m`), compared with the pins; `--write-platform` rewrites them (for the
               freeze, on the qualification host, with the pinned interpreter; refused when any reading fails).
  driver-diff  the DRIVER_DIFF.md generator: difflib.SequenceMatcher(autojunk=False), 3 lines of context, unified
               hunk headers; each hunk's touched top-level definitions from the AST line ranges of the CHANGED lines of
               both files; hunk classes and header text CARRIED from the committed DRIVER_DIFF.md. It first
               REPRODUCES the committed DRIVER_DIFF.md from the committed driver byte for byte (else it refuses,
               GENERATOR_NOT_VALIDATED); then it generates the file for the working driver; `--write` writes it.
               A class is carried from the committed hunk with the same touched-definition set (the i-th such hunk
               to the i-th); a hunk with no counterpart needs `--classes '{"<n>": "LIFECYCLE", ...}'`; a hunk touching
               a carried (text-identical) definition is SCIENCE-GLUE (MUST NOT OCCUR) and the tool fails. The carried
               definitions are those the COMMITTED file's header lists (validated above against the committed driver)
               together with those text-identical in the working driver: a change inside a carried function's body
               (which takes it out of the working driver's text-identical set) is therefore still SCIENCE-GLUE and
               refused, and `--classes` cannot reclassify it (reviewQ6 F-4).
  check        helpers + driver-diff, dry-run: exit 0 only when nothing is stale.
  apply        the MECHANICAL apply step of the user's section-11.2 ruling, option (a) (protocol section 11.2): the
               canonical rule outputs A of a DESIGNATED derivation (code/mbs308_derive.py, from the designated
               pre-freeze measurements) are written into the driver's five constants MEM_CAP_BYTES, MEM_POLL_S,
               FREE_MEM_MIN_BYTES, EXCL_CPU_PCT and EXCL_ALLOW and into the protocol's rule-output table. Refused
               unless the derivation is designated, its status is OK with every built-in rule check holding, it is
               reproduced here from the committed evidence it names, and the driver's bytes are the measured bytes.
               Nothing else may change: every other top-level statement of the driver and every byte of the protocol
               outside the table stay identical (checked), and DRIVER_DIFF.md is regenerated by the validated
               generator. Dry-run by default; `--write` writes. No value is ever typed by hand.

    python3.14 -I -S -B mbs308_repin.py helpers [--code DIR] [--write]
    python3.14 -I -S -B mbs308_repin.py platform [--code DIR] [--write-platform]
    python3.14 -I -S -B mbs308_repin.py driver-diff [--ns DIR] [--repo DIR] [--classes JSON] [--write]
    python3.14 -I -S -B mbs308_repin.py check [--ns DIR]
    python3.14 -I -S -B mbs308_repin.py apply --derivation FILE [--ns DIR] [--repo DIR] [--classes JSON] [--write]
Exit codes: 0 up to date (or written), 1 stale (dry-run), 2 refused.
"""
from __future__ import annotations

import argparse
import ast
import difflib
import hashlib
import json
import os
import re
import subprocess
import sys
from fractions import Fraction as F
from pathlib import Path

HERE = Path(__file__).resolve()
NS = HERE.parents[1]
REPO = HERE.parents[4]
NS_REL = "level4/closure_proofs/p5y_k5_cell308_mbs_r1"
DRIVER = "mbs308_driver.py"
DIFF_NAME = "DRIVER_DIFF.md"
MBR1_DRIVER_REL = "level4/closure_proofs/p5y_k5_cell308_mb_r1/code/mb308_driver.py"
MBR1_FREEZE_R3 = "c46434a399eca18a709616a4a4d51918d1a30298"
GENV = {"PATH": "/usr/bin:/bin", "LC_ALL": "C", "GIT_OPTIONAL_LOCKS": "0"}
CLASSES = ("IDENTITY", "IDENTITY + LIFECYCLE", "LIFECYCLE")
SCIENCE_GLUE_CLASS = "SCIENCE-GLUE (MUST NOT OCCUR)"


class Refused(Exception):
    def __init__(self, code: str, detail: str = ""):
        super().__init__(f"{code}: {detail}" if detail else code)
        self.code = code


def sha(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def _write_atomic(path: Path, data: bytes) -> None:
    tmp = path.with_name(f".{path.name}.repin-{os.getpid()}")
    with open(tmp, "xb") as fh:
        fh.write(data)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)


def _dict_literal(src: str, name: str) -> tuple:
    """(the dict of string constants bound to the module-level `name`, its source segment). Exactly one binding."""
    found = [n for n in ast.parse(src).body if isinstance(n, ast.Assign) and
             [getattr(t, "id", None) for t in n.targets] == [name]]
    if len(found) != 1 or not isinstance(found[0].value, ast.Dict):
        raise Refused("TABLE_NOT_FOUND", f"{name} must be bound exactly once to a dict literal")
    d = {}
    for k, v in zip(found[0].value.keys, found[0].value.values):
        if not (isinstance(k, ast.Constant) and isinstance(k.value, str) and isinstance(v, ast.Constant) and
                isinstance(v.value, str)):
            raise Refused("TABLE_NOT_LITERAL", f"{name} must map string constants to string constants")
        d[k.value] = v.value
    return d, ast.get_source_segment(src, found[0])


def _rewrite_table(src: str, name: str, new: dict) -> str:
    """Replace the values of `name`'s dict literal for the keys in `new`, each `"key": "old"` pair exactly once inside
    the table's own source segment; every other byte of the file is unchanged."""
    old, seg = _dict_literal(src, name)
    out = seg
    for k, v in new.items():
        pair = f"{json.dumps(k)}: {json.dumps(old[k])}"
        if out.count(pair) != 1:
            raise Refused("TABLE_PAIR_AMBIGUOUS", f"{name}[{k}]")
        out = out.replace(pair, f"{json.dumps(k)}: {json.dumps(v)}")
    if src.count(seg) != 1:
        raise Refused("TABLE_SEGMENT_AMBIGUOUS", name)
    res = src.replace(seg, out)
    got, _ = _dict_literal(res, name)
    if got != dict(old, **new):
        raise Refused("TABLE_REWRITE_CHECK", name)
    return res


# ------------------------------------------------------------------ helpers
def helper_status(code: Path) -> dict:
    src = (code / DRIVER).read_text()
    pins, _ = _dict_literal(src, "HELPER_SHA256")
    rows = {}
    for name, pinned in sorted(pins.items()):
        p = code / name
        actual = sha(p.read_bytes()) if p.is_file() else None
        rows[name] = {"pinned": pinned, "actual": actual, "stale": actual != pinned}
    return {"code_dir": str(code), "helpers": rows, "stale": sorted(k for k, v in rows.items() if v["stale"]),
            "missing": sorted(k for k, v in rows.items() if v["actual"] is None)}


def repin_helpers(code: Path, write: bool) -> dict:
    st = helper_status(code)
    if st["missing"]:
        raise Refused("HELPER_MISSING", ", ".join(st["missing"]))
    st["written"] = False
    if write and st["stale"]:
        drv = code / DRIVER
        src = drv.read_text()
        new = _rewrite_table(src, "HELPER_SHA256", {k: st["helpers"][k]["actual"] for k in st["stale"]})
        _write_atomic(drv, new.encode())
        st["written"] = True
        st["after"] = helper_status(code)["stale"]
    return st


# ------------------------------------------------------------------ platform pins
def platform_readings(pins: dict) -> dict:
    """The driver's platform_readings(), on this host with this interpreter (same commands, same host helper)."""
    sys.path.insert(0, str(HERE.parent))
    import mbs308_host as HOST
    exe = os.path.realpath(sys.executable)
    lib = pins["libpython"]

    def fsha(p):
        try:
            return hashlib.sha256(Path(p).read_bytes()).hexdigest()
        except OSError:
            return None
    build = HOST._run(["/usr/bin/sw_vers", "-buildVersion"])
    arch = HOST._run(["/usr/bin/uname", "-m"])
    return {"python_executable": exe, "python_sha256": fsha(exe), "libpython": lib, "libpython_sha256": fsha(lib),
            "python_version": sys.version.split()[0], "python_sys_version": sys.version,
            "os_build": (build or "").strip() or None, "arch": (arch or "").strip() or None}


def platform_status(code: Path) -> dict:
    pins, _ = _dict_literal((code / DRIVER).read_text(), "PLATFORM_PINS")
    got = platform_readings(pins)
    if set(got) != set(pins):
        raise Refused("PLATFORM_KEYS", f"readings {sorted(got)} vs pins {sorted(pins)}")
    rows = {k: {"pinned": pins[k], "reading": got[k], "differs": got[k] != pins[k]} for k in sorted(pins)}
    return {"code_dir": str(code), "interpreter": sys.executable, "pins": rows,
            "differs": sorted(k for k, v in rows.items() if v["differs"]),
            "unreadable": sorted(k for k, v in got.items() if v is None)}


def repin_platform(code: Path, write: bool) -> dict:
    st = platform_status(code)
    st["written"] = False
    if write and st["differs"]:
        if st["unreadable"]:
            raise Refused("PLATFORM_READING_FAILED", ", ".join(st["unreadable"]))
        drv = code / DRIVER
        new = _rewrite_table(drv.read_text(), "PLATFORM_PINS", {k: st["pins"][k]["reading"] for k in st["differs"]})
        _write_atomic(drv, new.encode())
        st["written"] = True
        st["after"] = platform_status(code)["differs"]
    return st


# ------------------------------------------------------------------ the DRIVER_DIFF.md generator
def _node_label(n: ast.AST, first: bool) -> str:
    if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        return n.name
    if isinstance(n, (ast.Import, ast.ImportFrom)):
        return "<imports>"
    if first and isinstance(n, ast.Expr) and isinstance(n.value, ast.Constant) and isinstance(n.value.value, str):
        return "<module docstring>"
    return "<module-level assignment / statement>"


def _line_owner(src: str) -> dict:
    """line number (1-based) -> the label of the top-level statement whose line range (decorators included) holds it."""
    out = {}
    body = ast.parse(src).body
    for i, n in enumerate(body):
        start = min([n.lineno] + [d.lineno for d in getattr(n, "decorator_list", [])])
        for ln in range(start, n.end_lineno + 1):
            out[ln] = _node_label(n, i == 0)
    return out


def carried_names(base: str, new: str) -> list:
    """Top-level definitions present in both files with text-identical source segments."""
    def segs(src):
        return {n.name: ast.get_source_segment(src, n) for n in ast.parse(src).body
                if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))}
    a, b = segs(base), segs(new)
    return sorted(k for k in a if k in b and a[k] == b[k])


def _range(start: int, stop: int) -> str:
    """difflib's unified-diff range format (_format_range_unified)."""
    beginning, length = start + 1, stop - start
    if length == 1:
        return f"{beginning}"
    if not length:
        beginning -= 1
    return f"{beginning},{length}"


def hunks(base: str, new: str) -> list:
    a, b = base.splitlines(keepends=True), new.splitlines(keepends=True)
    own_a, own_b = _line_owner(base), _line_owner(new)
    out = []
    for group in difflib.SequenceMatcher(None, a, b, autojunk=False).get_grouped_opcodes(3):
        f, l = group[0], group[-1]
        lines = [f"@@ -{_range(f[1], l[2])} +{_range(f[3], l[4])} @@\n"]
        touched = set()
        for tag, i1, i2, j1, j2 in group:
            if tag == "equal":
                lines += [" " + x for x in a[i1:i2]]
                continue
            if tag in ("replace", "delete"):
                lines += ["-" + x for x in a[i1:i2]]
                touched |= {own_a[i + 1] for i in range(i1, i2) if i + 1 in own_a}
            if tag in ("replace", "insert"):
                lines += ["+" + x for x in b[j1:j2]]
                touched |= {own_b[j + 1] for j in range(j1, j2) if j + 1 in own_b}
        text = "".join(x if x.endswith("\n") else x + "\n\\ No newline at end of file\n" for x in lines)
        out.append({"text": text, "touched": sorted(touched)})
    return out


_HUNK_HDR = re.compile(r"^### Hunk (\d+): (.+?); (.*)$")
CARRIED_LINE = "* The carried (text-identical) functions: "


def parse_committed(md: str) -> dict:
    """The committed file's carried parts: its header lines (for the carried text), each hunk's class and touched
    set, in order, and the carried (text-identical) definitions its header lists (exactly one such line)."""
    lines = md.split("\n")
    classes = []
    for ln in lines:
        m = _HUNK_HDR.match(ln)
        if m:
            classes.append({"n": int(m.group(1)), "class": m.group(2), "touched": m.group(3).split(", ")})
    head_end = lines.index("## Hunk index")
    listed = [ln for ln in lines[:head_end] if ln.startswith(CARRIED_LINE)]
    if len(listed) != 1:
        raise Refused("CARRIED_LIST", "the committed DRIVER_DIFF.md must list the carried definitions exactly once")
    return {"header": lines[:head_end], "hunks": classes, "carried": re.findall(r"`([^`]+)`", listed[0])}


def render(base: str, new: str, committed: dict, classes_override: dict | None = None) -> tuple:
    """(the DRIVER_DIFF.md text, the per-hunk class decisions). Refuses on a hunk without a class."""
    hs = hunks(base, new)
    carried_now = set(carried_names(base, new))
    # F-4: the definitions carried AT THE COMMIT stay science glue: a change inside one of them is refused, not
    # silently dropped from the carried list (a body change takes it out of the text-identical set of `new`)
    glue = carried_now | set(committed.get("carried", []))
    by_set: dict = {}
    for h in committed["hunks"]:
        by_set.setdefault(tuple(h["touched"]), []).append(h["class"])
    used: dict = {}
    decisions = []
    for i, h in enumerate(hs, 1):
        key = tuple(h["touched"])
        k = used.get(key, 0)
        used[key] = k + 1
        if glue & set(h["touched"]):
            cls, how = SCIENCE_GLUE_CLASS, "touches a carried definition"
        elif classes_override and str(i) in classes_override:
            cls, how = classes_override[str(i)], "given (--classes)"
        elif k < len(by_set.get(key, [])):
            cls, how = by_set[key][k], "carried"
        else:
            raise Refused("HUNK_WITHOUT_CLASS", f"hunk {i} touches {list(key)}: give its class with --classes")
        if cls not in CLASSES + (SCIENCE_GLUE_CLASS,):
            raise Refused("UNKNOWN_CLASS", f"hunk {i}: {cls}")
        h["class"] = cls
        decisions.append({"hunk": i, "class": cls, "how": how, "touched": h["touched"]})
    counts: dict = {}
    for h in hs:
        counts[h["class"]] = counts.get(h["class"], 0) + 1
    hdr = []
    for ln in committed["header"]:
        if ln.startswith("* Base: "):
            ln = re.sub(r"sha256 `[0-9a-f]{64}`", f"sha256 `{sha(base.encode())}`", ln)
        elif ln.startswith("* New: "):
            ln = re.sub(r"sha256 `[0-9a-f]{64}`", f"sha256 `{sha(new.encode())}`", ln)
        elif ln.startswith("* Hunks: "):
            ln = f"* Hunks: {len(hs)}; by class: " + ", ".join(f"{c} {n}" for c, n in sorted(counts.items())) + "."
        elif ln.startswith(CARRIED_LINE):
            ln = CARRIED_LINE + ", ".join(f"`{n}`" for n in sorted(carried_now)) + "."
        hdr.append(ln)
    out = ["\n".join(hdr), "## Hunk index\n", "| # | class | top-level definitions touched |", "|---|---|---|"]
    for i, h in enumerate(hs, 1):
        out.append(f"| {i} | {h['class']} | " + ", ".join(f"`{t}`" for t in h["touched"]) + " |")
    out.append("\n## Full diff, hunk by hunk\n")
    for i, h in enumerate(hs, 1):
        out.append(f"### Hunk {i}: {h['class']}; {', '.join(h['touched'])}\n")
        out.append("```diff\n" + h["text"] + "```\n")
    return "\n".join(out) + "\n", decisions


def git_show(repo: Path, rev: str, rel: str) -> bytes | None:
    p = subprocess.run(["/usr/bin/git", "-C", str(repo), "show", f"{rev}:{rel}"], capture_output=True, env=GENV,
                       stdin=subprocess.DEVNULL)
    return p.stdout if p.returncode == 0 else None


def driver_diff(ns: Path, repo: Path, write: bool, classes_override: dict | None = None,
                new_text: str | None = None) -> dict:
    """`new_text` (the apply step): the driver text the file is generated FOR, instead of the working driver's (the
    generated text is then returned as `text` and nothing is written here)."""
    base_b = git_show(repo, MBR1_FREEZE_R3, MBR1_DRIVER_REL)
    head_drv = git_show(repo, "HEAD", f"{NS_REL}/code/{DRIVER}")
    head_md = git_show(repo, "HEAD", f"{NS_REL}/{DIFF_NAME}")
    if base_b is None or head_drv is None or head_md is None:
        raise Refused("GIT_READ_FAILED", "MB r1's driver at c46434a3, or the committed driver / DRIVER_DIFF.md")
    base = base_b.decode()
    committed = parse_committed(head_md.decode())
    # 1. validation: the committed file, regenerated from the committed driver with its own classes, byte for byte
    regen, _ = render(base, head_drv.decode(), committed)
    if regen.encode() != head_md:
        raise Refused("GENERATOR_NOT_VALIDATED", "the committed DRIVER_DIFF.md is not reproduced byte for byte")
    # 2. the working driver (or the text the apply step is about to write)
    new = (ns / "code" / DRIVER).read_text() if new_text is None else new_text
    text, decisions = render(base, new, committed, classes_override)
    cur = (ns / DIFF_NAME).read_bytes() if (ns / DIFF_NAME).exists() else None
    out = {"validated_against_head": True, "hunks": len(decisions), "decisions": decisions,
           "science_glue_hunks": [d["hunk"] for d in decisions if d["class"] == SCIENCE_GLUE_CLASS],
           "stale": cur != text.encode(), "written": False, "sha256": sha(text.encode())}
    if out["science_glue_hunks"]:
        raise Refused("SCIENCE_GLUE_HUNK", json.dumps(out["science_glue_hunks"]))
    if new_text is not None:
        out["text"] = text
        return out
    if write and out["stale"]:
        _write_atomic(ns / DIFF_NAME, text.encode())
        out["written"] = True
    return out


# ------------------------------------------------------------------ the apply step (section 11.2, option (a))
RULE_CONSTANTS = ("MEM_CAP_BYTES", "MEM_POLL_S", "FREE_MEM_MIN_BYTES", "EXCL_CPU_PCT", "EXCL_ALLOW")
PROTOCOL_NAME = "MBS308_PROTOCOL_DRAFT.md"
TABLE_BEGIN = "<!-- MBS308-RULE-OUTPUTS-BEGIN (written only by code/mbs308_repin.py apply; never by hand) -->"
TABLE_END = "<!-- MBS308-RULE-OUTPUTS-END -->"
PROVISIONAL = "PROVISIONAL (pre-freeze build; not a rule output)"
ALLOW_INDENT = " " * 24
LINE_WIDTH = 120


def _derive():
    sys.path.insert(0, str(HERE.parent))
    import mbs308_derive as DV
    return DV


def poll_literal(canon: str) -> str:
    """The source literal of a CANONICAL MEM_POLL_S output (readings R1, item 6; owner supplement 2, section 2): "2"
    (the re-checked value, unchanged) as `2.0`, "1/2" (the rule's clip) as `0.5`. Anything else REFUSES: no quotient
    is ever written into the driver, so nothing is rounded, no decimal precision chosen and no p / q expression made."""
    DV = _derive()
    try:
        x = F(canon) if isinstance(canon, str) else None
    except (ValueError, ZeroDivisionError):
        x = None
    if x is None or x not in DV.POLL_VALUES or DV.RR.fstr(x) != canon:
        raise Refused("OUTPUT_NOT_CANONICAL", "MEM_POLL_S is not a canonical rule output (2 or 1/2)")
    if x.denominator == 1:
        return f"{x.numerator}.0"
    return "0.5"


def allow_literal(names: list) -> str:
    """`frozenset({...})` of the sorted names, wrapped at 120 columns with the driver's continuation indent."""
    names = sorted(names)
    if len(set(names)) != len(names) or not names or any(not isinstance(n, str) or not n or '"' in n or "\\" in n
                                                           or "\n" in n for n in names):
        raise Refused("OUTPUT", "EXCL_ALLOW must be a non-empty list of distinct plain names")
    lines, cur = [], "EXCL_ALLOW = frozenset({"
    for i, n in enumerate(names):
        item = json.dumps(n) + ("," if i < len(names) - 1 else "})")
        if len(cur) + len(item) + (0 if cur.endswith("{") else 1) > LINE_WIDTH:
            lines.append(cur)
            cur = ALLOW_INDENT + item
        else:
            cur += ("" if cur.endswith("{") else " ") + item
    lines.append(cur)
    return "\n".join(lines)[len("EXCL_ALLOW = "):]


def output_literals(outputs: dict) -> dict:
    """The five source literals. Refuses any output that is not in the canonical form the rule text fixes
    (mbs308_derive.form_reasons: readings R1, item 6): the apply step never writes anything else into the driver."""
    DV = _derive()
    if not isinstance(outputs, dict) or set(outputs) != set(RULE_CONSTANTS):
        raise Refused("OUTPUT", "the five canonical outputs are not all present")
    forms = DV.form_reasons(dict(outputs, EXCL_ALLOW=sorted(outputs["EXCL_ALLOW"])
                                 if isinstance(outputs["EXCL_ALLOW"], list) and all(
                                     isinstance(n, str) for n in outputs["EXCL_ALLOW"]) else outputs["EXCL_ALLOW"]))
    if forms:
        raise Refused("OUTPUT_NOT_CANONICAL", ", ".join(forms))
    return {"MEM_CAP_BYTES": str(outputs["MEM_CAP_BYTES"]), "MEM_POLL_S": poll_literal(outputs["MEM_POLL_S"]),
            "FREE_MEM_MIN_BYTES": str(outputs["FREE_MEM_MIN_BYTES"]), "EXCL_CPU_PCT": f"{outputs['EXCL_CPU_PCT']}.0",
            "EXCL_ALLOW": allow_literal(outputs["EXCL_ALLOW"])}


def _top_segments(src: str) -> list:
    return [(getattr(n.targets[0], "id", None) if isinstance(n, ast.Assign) and len(n.targets) == 1 else None,
             ast.get_source_segment(src, n)) for n in ast.parse(src).body]


def apply_constants(src: str, outputs: dict) -> str:
    """The driver text with exactly the VALUE expressions of the five rule constants replaced by the canonical
    outputs' literals. Checked: the new text parses, carries exactly the outputs (read back by the derivation module's
    exact reader), and every other top-level statement is byte-identical and in the same order."""
    DV = _derive()
    lits = output_literals(outputs)
    raw = src.encode()
    starts = [0]
    for ln in raw.splitlines(keepends=True):
        starts.append(starts[-1] + len(ln))
    spans = []
    for name in RULE_CONSTANTS:
        found = [n for n in ast.parse(src).body if isinstance(n, ast.Assign) and
                 [getattr(t, "id", None) for t in n.targets] == [name]]
        if len(found) != 1:
            raise Refused("CONSTANT_NOT_FOUND", f"{name} must be bound exactly once at module level")
        v = found[0].value
        spans.append((starts[v.lineno - 1] + v.col_offset, starts[v.end_lineno - 1] + v.end_col_offset, lits[name]))
    out = raw
    for a, b, lit in sorted(spans, reverse=True):
        out = out[:a] + lit.encode() + out[b:]
    new = out.decode()
    try:
        got = DV.driver_outputs(new)
    except DV.DeriveRefusal as e:
        raise Refused("APPLY_CHECK", str(e))
    want = {k: (sorted(outputs[k]) if k == "EXCL_ALLOW" else outputs[k]) for k in RULE_CONSTANTS}
    if {k: (F(got[k]) if k == "MEM_POLL_S" else got[k]) for k in RULE_CONSTANTS} != \
            {k: (F(want[k]) if k == "MEM_POLL_S" else want[k]) for k in RULE_CONSTANTS}:
        raise Refused("APPLY_CHECK", "the rewritten driver does not carry exactly the outputs")
    a_seg, b_seg = _top_segments(src), _top_segments(new)
    if len(a_seg) != len(b_seg) or any(x != y for x, y in zip(a_seg, b_seg) if x[0] not in RULE_CONSTANTS) or \
            [x[0] for x in a_seg] != [y[0] for y in b_seg]:
        raise Refused("APPLY_CHECK", "a statement other than the five rule constants would change")
    return new


def render_table(outputs: dict, status: str) -> str:
    rows = [TABLE_BEGIN, "| constant | value the driver carries | status |", "|---|---|---|"]
    for k in RULE_CONSTANTS:
        v = outputs[k]
        val = (", ".join(f"`{n}`" for n in sorted(v)) + f" ({len(v)} names)") if k == "EXCL_ALLOW" else f"`{v}`"
        rows.append(f"| `{k}` | {val} | {status} |")
    rows.append(TABLE_END)
    return "\n".join(rows)


def apply_protocol(text: str, outputs: dict, status: str) -> str:
    """The protocol with its rule-output table (between the two markers, each present exactly once) rewritten; the
    text before the first marker and after the second is carried byte for byte."""
    if text.count(TABLE_BEGIN) != 1 or text.count(TABLE_END) != 1 or text.index(TABLE_BEGIN) > text.index(TABLE_END):
        raise Refused("PROTOCOL_TABLE", "the rule-output table markers are not present exactly once, in order")
    a, b = text.index(TABLE_BEGIN), text.index(TABLE_END) + len(TABLE_END)
    return text[:a] + render_table(outputs, status) + text[b:]


def table_outputs(text: str) -> dict:
    """The values the protocol's rule-output table states (for the static consistency check)."""
    if text.count(TABLE_BEGIN) != 1 or text.count(TABLE_END) != 1:
        raise Refused("PROTOCOL_TABLE", "markers")
    out = {}
    for ln in text[text.index(TABLE_BEGIN):text.index(TABLE_END)].splitlines():
        cells = [c.strip() for c in ln.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].startswith("`") and cells[0].strip("`") in RULE_CONSTANTS:
            k = cells[0].strip("`")
            names = re.findall(r"`([^`]+)`", cells[1])
            out[k] = sorted(names) if k == "EXCL_ALLOW" else (names[0] if k == "MEM_POLL_S" else int(names[0]))
            out.setdefault("_status", {})[k] = cells[2]
    return out


def derivation_reasons(d, ns: Path, repo: Path) -> list:
    """Why a derivation may NOT be applied (empty = it may): it must be designated, OK with every built-in rule check
    holding, name the committed evidence by sha256, and be exactly what the derivation tool computes from that
    evidence."""
    DV = _derive()
    if not isinstance(d, dict) or d.get("schema") != DV.DERIVATION_SCHEMA:
        return ["NOT_A_DERIVATION"]
    r = []
    if d.get("designated") is not True:
        r.append("NOT_DESIGNATED")
    if d.get("status") != "OK":
        r.append("STATUS_NOT_OK")
    for st in d.get("fail_closed_statuses") or []:           # STOP BEFORE FREEZE (owner supplement 2): named as it is
        r.append(str(st))
    if d.get("stop_before_freeze") is not False:
        r.append("STOP_BEFORE_FREEZE")
    if (d.get("checks") or {}).get("all_hold") is not True or any(
            v is not True for v in (d.get("checks") or {}).values()):
        r.append("A_RULE_CHECK_DOES_NOT_HOLD")
    outs = d.get("outputs") or {}
    if set(outs) != set(RULE_CONSTANTS) or any(outs[k] is None for k in outs):
        r.append("OUTPUT_MISSING")
    elif DV.form_reasons(outs):
        r += DV.form_reasons(outs)
    evp = ns / "evidence_prefreeze" / DV.EVIDENCE_NAME
    try:
        raw = evp.read_bytes()
    except OSError:
        return r + ["EVIDENCE_FILE_MISSING"]
    if sha(raw) != (d.get("evidence") or {}).get("sha256"):
        r.append("EVIDENCE_SHA256_DIFFERS")
    try:
        cfg = json.loads((ns / "config" / "MBS308_QUALIFICATION_CASES.json").read_text())
        again = DV.derivation(json.loads(raw), evidence_sha256=sha(raw), base_names=DV.base_names_of(cfg, repo),
                              h3_readings=cfg["r_allow_h3_readings"]["readings"], plan=DV.plan_of(cfg),
                              rules_sha256=sha((ns / "code" / "mbs308_rrules.py").read_bytes()),
                              tool_sha256=sha((ns / "code" / "mbs308_derive.py").read_bytes()))
        if again["outputs"] != outs or again["status"] != d.get("status") or again["checks"] != d.get("checks"):
            r.append("NOT_REPRODUCED_FROM_THE_EVIDENCE")
    except (DV.DeriveRefusal, OSError, ValueError, KeyError) as e:
        r.append(f"REDERIVATION_FAILED_{type(e).__name__}")
    return r


def apply_outputs(ns: Path, repo: Path, derivation_path: Path, write: bool, classes_override: dict | None = None) -> dict:
    DV = _derive()
    try:
        raw = Path(derivation_path).read_bytes()
        d = json.loads(raw)
    except (OSError, ValueError) as e:
        raise Refused("DERIVATION_UNREADABLE", type(e).__name__)
    why = derivation_reasons(d, ns, repo)
    if why:
        raise Refused("DERIVATION_NOT_APPLICABLE", ", ".join(why))
    outs = d["outputs"]
    drv, proto = ns / "code" / DRIVER, ns / "protocol" / PROTOCOL_NAME
    src = drv.read_text()
    cur = DV.driver_outputs(src)
    same = all((F(cur[k]) == F(outs[k])) if k == "MEM_POLL_S" else (cur[k] == (sorted(outs[k]) if k == "EXCL_ALLOW"
                                                                             else outs[k])) for k in RULE_CONSTANTS)
    measured = sha(src.encode()) == d["evidence"]["driver_sha256"]
    if not measured and not same:
        raise Refused("DRIVER_NOT_THE_MEASURED_BYTES", "the driver changed since the designated measurement")
    status = f"RULE OUTPUT A (designated derivation sha256 `{sha(raw)}`)"
    new_src = apply_constants(src, outs)
    new_proto = apply_protocol(proto.read_text(), outs, status)
    dd = driver_diff(ns, repo, False, classes_override, new_text=new_src)
    changes = {k: {"from": cur[k] if k != "EXCL_ALLOW" else len(cur[k]), "to": outs[k] if k != "EXCL_ALLOW" else
                   len(outs[k])} for k in RULE_CONSTANTS}
    out = {"derivation_sha256": sha(raw), "changes": changes,
           "allow_added": sorted(set(outs["EXCL_ALLOW"]) - set(cur["EXCL_ALLOW"])),
           "allow_removed": sorted(set(cur["EXCL_ALLOW"]) - set(outs["EXCL_ALLOW"])),
           "driver_changes": new_src != src, "protocol_changes": new_proto != proto.read_text(),
           "driver_diff_changes": dd["text"].encode() != ((ns / DIFF_NAME).read_bytes() if (ns / DIFF_NAME).exists()
                                                         else None),
           "driver_sha256_after": sha(new_src.encode()), "written": False}
    out["stale"] = out["driver_changes"] or out["protocol_changes"] or out["driver_diff_changes"]
    if out["stale"] and write:                   # dry-run by default: nothing is written without --write
        _write_atomic(drv, new_src.encode())
        _write_atomic(proto, new_proto.encode())
        _write_atomic(ns / DIFF_NAME, dd["text"].encode())
        out["written"] = True
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("what", choices=("helpers", "platform", "driver-diff", "check", "apply"))
    ap.add_argument("--derivation", help="apply: the designated derivation (JSON) written by mbs308_derive.py")
    ap.add_argument("--code", help="code directory (default: this namespace's code/)")
    ap.add_argument("--ns", help="namespace directory (driver-diff / check; default: this namespace)")
    ap.add_argument("--repo", help="repository (driver-diff; default: this namespace's repository)")
    ap.add_argument("--classes", help='JSON {"<hunk number>": "<class>"} for hunks without a committed counterpart')
    ap.add_argument("--write", action="store_true", help="helpers / driver-diff: write the stale values / file")
    ap.add_argument("--write-platform", action="store_true", help="platform: rewrite PLATFORM_PINS (the freeze)")
    a = ap.parse_args(argv)
    ns = Path(a.ns).resolve() if a.ns else NS
    code = Path(a.code).resolve() if a.code else ns / "code"
    try:
        if a.what == "helpers":
            r = repin_helpers(code, a.write)
            stale = bool(r["stale"]) and not r["written"]
        elif a.what == "platform":
            if a.write:
                raise Refused("FLAG", "platform pins are written only with --write-platform")
            r = repin_platform(code, a.write_platform)
            stale = bool(r["differs"]) and not r["written"]
        elif a.what == "driver-diff":
            r = driver_diff(ns, Path(a.repo).resolve() if a.repo else REPO, a.write,
                            json.loads(a.classes) if a.classes else None)
            stale = r["stale"] and not r["written"]
        elif a.what == "apply":
            if not a.derivation:
                raise Refused("FLAG", "apply needs --derivation FILE")
            r = apply_outputs(ns, Path(a.repo).resolve() if a.repo else REPO, Path(a.derivation), a.write,
                              json.loads(a.classes) if a.classes else None)
            stale = r["stale"] and not r["written"]
        else:
            if a.write or a.write_platform:
                raise Refused("FLAG", "check is dry-run only")
            r = {"helpers": helper_status(code), "driver_diff": driver_diff(ns, REPO, False)}
            stale = bool(r["helpers"]["stale"]) or r["driver_diff"]["stale"]
    except Refused as e:
        print(json.dumps({"refused": e.code, "detail": str(e)}))
        return 2
    print(json.dumps(r, indent=1, sort_keys=True))
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
