"""The addressable primitive exogenous random field.

Every raw draw the simulator can ever need is a **pure function of its address**:

    (SEED_NAMESPACE, detector, m, k, replicate_id, cycle_id,
     primitive_type, primitive_index)  ->  float64

The address deliberately contains **no** policy identity, no sensitivity variant,
no ``s1`` multiplier, no live-set position, no stopping time, no branch order and
no count of previously consumed draws.  That is the whole repair: a value can be
queried at any time, in any order, by any variant, and it is the same value.

Implementation.  Values are materialised in **blocks** of ``BLOCK_LEN``
observations, one block per ``(cell, cycle, primitive_type, block_index)``.  A
block is generated by a counter-based Philox stream keyed only on that address,
so block ``b`` is independent of whether block ``b-1`` was ever generated and of
how many draws any replicate consumed.  Overflow is therefore not a special
case: observation ``t`` simply lives in block ``t // BLOCK_LEN`` at offset
``t % BLOCK_LEN``, for every ``t``, forever.

``BLOCK_LEN`` is deliberately small (512) so that overflow past the first block
is **routine** rather than hypothetical -- roughly 3% of cycles at the operating
ARL -- and is exercised by the ordinary experiment, not only by a contrived test.
"""
from __future__ import annotations

import hashlib
from functools import lru_cache

import numpy as np

#: Entropy namespace.  Fixed forever; never varied by policy or variant.
SEED_NAMESPACE = 0x50365232_42435250          # "P6R2bCRP"
#: Observations materialised per block.  Small on purpose: overflow is routine.
BLOCK_LEN = 512

#: primitive types.  Distinct streams, independently addressable.
MONITOR = "monitor"          # raw observations feeding the detector
FRESH = "fresh"              # post-alarm fresh baseline observations
INIT = "init"                # initialisation randomness
AUX = "aux"                  # any auxiliary simulator randomness
PRIMITIVE_TYPES = (MONITOR, FRESH, INIT, AUX)


def _tag(s: str) -> int:
    return int.from_bytes(hashlib.sha256(s.encode()).digest()[:8], "big")


def address_key(detector: str, m: int, k: int, cycle: int,
                primitive_type: str, block_index: int) -> tuple:
    """The full address key of one block.  Contains nothing policy-dependent."""
    if primitive_type not in PRIMITIVE_TYPES:
        raise ValueError(f"unknown primitive type {primitive_type!r}")
    return (SEED_NAMESPACE, _tag(detector), int(m), int(k), int(cycle),
            _tag(primitive_type), int(block_index))


@lru_cache(maxsize=64)
def _block_cached(detector: str, m: int, k: int, cycle: int,
                  primitive_type: str, block_index: int, n_rep: int,
                  width: int) -> np.ndarray:
    ss = np.random.SeedSequence(
        list(address_key(detector, m, k, cycle, primitive_type, block_index)))
    rng = np.random.Generator(np.random.Philox(ss))
    a = rng.standard_normal((int(n_rep), int(width)))
    a.flags.writeable = False
    return a


def block(detector: str, m: int, k: int, cycle: int, primitive_type: str,
          block_index: int, n_rep: int, width: int = BLOCK_LEN) -> np.ndarray:
    """``(n_rep, width)`` block of primitives at one address.  Read-only."""
    return _block_cached(detector, m, k, int(cycle), primitive_type,
                         int(block_index), int(n_rep), int(width))


def monitor(detector: str, m: int, k: int, replicate: int, cycle: int,
            index: int, n_rep: int) -> float:
    """One monitor observation, by address.  Works for ANY ``index``."""
    b, off = divmod(int(index), BLOCK_LEN)
    return float(block(detector, m, k, cycle, MONITOR, b, n_rep)[int(replicate), off])


def monitor_column(detector: str, m: int, k: int, cycle: int, index: int,
                   n_rep: int) -> np.ndarray:
    """All replicates' monitor observation at one ``index``.  Order-independent."""
    b, off = divmod(int(index), BLOCK_LEN)
    return block(detector, m, k, cycle, MONITOR, b, n_rep)[:, off]


def fresh(detector: str, m: int, k: int, cycle: int, n_rep: int) -> np.ndarray:
    """All replicates' post-alarm fresh primitive for one cycle."""
    return block(detector, m, k, cycle, FRESH, 0, n_rep, width=1)[:, 0]


def init(detector: str, m: int, k: int, n_rep: int) -> np.ndarray:
    """Initialisation primitive.  Addressable even when the experiment ignores it."""
    return block(detector, m, k, -1, INIT, 0, n_rep, width=1)[:, 0]


def aux(detector: str, m: int, k: int, cycle: int, index: int,
        n_rep: int) -> np.ndarray:
    """Auxiliary primitive stream.  Unused by this experiment; addressable anyway."""
    b, off = divmod(int(index), BLOCK_LEN)
    return block(detector, m, k, cycle, AUX, b, n_rep)[:, off]


def field_hash(detector: str, m: int, k: int, n_rep: int, n_cycles: int,
               max_block_index: int) -> str:
    """SHA-256 over every primitive block any variant could have touched.

    Exhaustive over the address space, and computed from the address alone, so
    it cannot depend on which variant asks for it.
    """
    h = hashlib.sha256()
    h.update(f"ns={SEED_NAMESPACE} det={detector} m={m} k={k} "
             f"n_rep={n_rep} n_cycles={n_cycles} blk={BLOCK_LEN}".encode())
    h.update(np.ascontiguousarray(init(detector, m, k, n_rep)).tobytes())
    for j in range(int(n_cycles)):
        h.update(np.ascontiguousarray(fresh(detector, m, k, j, n_rep)).tobytes())
        for b in range(int(max_block_index) + 1):
            h.update(np.ascontiguousarray(
                block(detector, m, k, j, MONITOR, b, n_rep)).tobytes())
    return h.hexdigest()


def clear_cache():
    _block_cached.cache_clear()
