#!/usr/bin/env python3
"""Regenerate the audit-only artifacts twice and verify byte stability offline."""
from __future__ import annotations

import argparse
import hashlib
import subprocess

from config import BASE, PY, RESULTS, ROOT, STARTING_HEAD, canonical_json, load


GENERATED = [
    "requirements.json",
    "results/evidence_audit.json",
    "results/ledger_derivation.json",
    "README.md",
    "REQUIREMENT_LEDGER.md",
    "EVIDENCE_MAP.md",
    "STATUS_TRANSITIONS.md",
    "CLAIM_FIREWALL.md",
    "OPEN_ITEMS.md",
]


def digest() -> str:
    value = hashlib.sha256()
    for relative in GENERATED:
        path = BASE / relative
        name, data = relative.encode(), path.read_bytes()
        value.update(len(name).to_bytes(8, "big")); value.update(name)
        value.update(len(data).to_bytes(8, "big")); value.update(data)
    return value.hexdigest()


def generate() -> None:
    subprocess.run([str(PY), str(BASE / "src/audit.py")], cwd=ROOT, check=True)
    subprocess.run([str(PY), str(BASE / "src/reports.py")], cwd=ROOT, check=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--establish", action="store_true")
    parser.add_argument("--check-run", action="store_true")
    parser.add_argument("--check-record", action="store_true")
    args = parser.parse_args()
    record_path = RESULTS / "reproduction.json"
    if args.check_record:
        record = load(record_path)
        actual = digest()
        passed = (record.get("status") == "PASS" and record.get("digest") == actual
                  and record.get("byte_stable") is True and record.get("offline") is True)
        print(f"terminal reproduction record: {'PASS' if passed else 'FAIL'} {actual}")
        return 0 if passed else 1
    before = digest()
    generate(); middle = digest()
    generate(); after = digest()
    stable = before == middle == after
    if args.establish:
        record = {
            "schema": "rebaseguard.final-level4-closure-reproduction.v1",
            "status": "PASS" if stable else "FAIL",
            "byte_stable": stable,
            "offline": True,
            "new_science_run": False,
            "generated_artifacts": GENERATED,
            "digest": after,
            "audit_start_head": STARTING_HEAD,
        }
        record_path.write_text(canonical_json(record))
    print(f"terminal generated bytes: {'PASS' if stable else 'FAIL'} {after}")
    return 0 if stable else 1


if __name__ == "__main__":
    raise SystemExit(main())
