import «LocationFamilyTrack3AB»

#print axioms RebaseguardLean.LocationFamilyTrack3AB.parameterScoreSum_eq_neg_conventional
#print axioms RebaseguardLean.LocationFamilyTrack3AB.stoppedScore_derivative_bridge
#print axioms RebaseguardLean.LocationFamilyTrack3AB.rho_scaling
#print axioms RebaseguardLean.LocationFamilyTrack3AB.locationFamily_derivative_spine
#print axioms RebaseguardLean.LocationFamilyTrack3AB.reflectPath_involutive
#print axioms RebaseguardLean.LocationFamilyTrack3AB.conventionalScoreSum_reflection
#print axioms RebaseguardLean.LocationFamilyTrack3AB.reflected_stopped_gain
#print axioms RebaseguardLean.LocationFamilyTrack3AB.reuseMean_odd
#print axioms RebaseguardLean.LocationFamilyTrack3AB.gaussian_score_sum_specialization
#print axioms RebaseguardLean.LocationFamilyTrack3AB.gaussian_gain_specialization
#print axioms RebaseguardLean.LocationFamilyTrack3AB.gamma_threshold_derivative_lt_neg_one
#print axioms RebaseguardLean.LocationFamilyTrack3AB.gamma_gt_two_full_reuse_derivative_lt_neg_one
#print axioms RebaseguardLean.LocationFamilyTrack3AB.raw_gain_ne_terminal_score_gain
#print axioms RebaseguardLean.LocationFamilyTrack3AB.gaussian_terminal_gain_eq_raw
