"""Generate opt_core.py MECHANICALLY from the frozen t3_patch.core and sr_o9_patch_certifier.contract_all: the frozen
text with exactly the listed substitutions (each asserted to occur exactly once). Re-running must reproduce the
committed file byte for byte."""
import ast
import inspect
from pathlib import Path

import t3_patch
import sr_o9_patch_certifier as PC

NS = Path(__file__).resolve().parents[1]

SUB_CORE = [
    ("    core_acc = PC.contract_all(g, pan, ctxt, cands, needed, shared_cache, stats)\n",
     "    core_acc = contract_all_memo(g, pan, ctxt, cands, needed, shared_cache, stats)\n"),
    ('    sides = {"L": ES.StripSide(g, g["L_c"], "L", shifts), "U": ES.StripSide(g, g["U_c"], "U", shifts)}\n',
     '    sides = {"L": OPT.StripSideMemo(g, g["L_c"], "L", shifts), "U": OPT.StripSideMemo(g, g["U_c"], "U", shifts)}\n'),
]
SUB_ALL = [
    ("def contract_all(g, pan, ctxt, cands, needed, shared_cache, stats):", "def contract_all_memo(g, pan, ctxt, cands, needed, shared_cache, stats):"),
    ("    evals = 0\n", "    evals = 0\n    memo = {}\n"),
    ("pd = OB.PanelDrift(sh, N) if s == 0 else RawShiftDrift(sh, N, s, z_c, h)",
     "pd = OB.PanelDrift(sh, N) if s == 0 else PC.RawShiftDrift(sh, N, s, z_c, h)"),
    ("coef, ex, ez = P.contract_O9(pd, cands[c], Rb, av)", "coef, ex, ez = OPT.contract_O9_memo(pd, cands[c], Rb, av, memo, c, kp)"),
]


def sub(src, subs):
    for a, b in subs:
        assert src.count(a) == 1, (a, src.count(a))
        src = src.replace(a, b)
    return src


def build():
    core = sub(inspect.getsource(t3_patch.core), SUB_CORE)
    allm = sub(inspect.getsource(PC.contract_all), SUB_ALL)
    head = ('"""GENERATED by make_opt_core.py: frozen t3_patch.core and sr_o9_patch_certifier.contract_all with the '
            'asserted substitutions\nlisted there (OPT-S strip memo, OPT-C O9 memo). All other text is frozen."""\n'
            "from t3_patch import *                                  # noqa: F401,F403  (T, EQ, PC, ES, BP, FC, arb, hashlib, fup)\n"
            "from t3_patch import _enc_exact                         # noqa: F401\n"
            "from sr_o9_patch_certifier import packet, OB, H, KMAX, D, Z   # noqa: F401\n"
            "import ps1_opt as OPT\n\n\n")
    return head + allm + "\n\n" + core


if __name__ == "__main__":
    (NS / "code/opt_core.py").write_text(build())
    print("generated opt_core.py")
