"""GENERATED by make_opt_core.py: frozen t3_patch.core and sr_o9_patch_certifier.contract_all with the asserted substitutions
listed there (OPT-S strip memo, OPT-C O9 memo). All other text is frozen."""
from t3_patch import *                                  # noqa: F401,F403  (T, EQ, PC, ES, BP, FC, arb, hashlib, fup)
from t3_patch import _enc_exact                         # noqa: F401
from sr_o9_patch_certifier import packet, OB, H, KMAX, D, Z   # noqa: F401
import ps1_opt as OPT


def contract_all_memo(g, pan, ctxt, cands, needed, shared_cache, stats):
    """Accumulate every needed (cand, s) contract over the panels, ascending kp."""
    P = packet()
    acc = {k: [[[arb(0)] * (D + 1) for _ in range(D + 1)], arb(0), arb(0)] for k in needed}
    shifts = sorted({s for _, s in needed})
    evals = 0
    memo = {}
    for kp in range(pan["n_z"]):
        h = pan["h"]
        z_lo = g["L_c"] + arb(2) * h * arb(kp)
        z_hi = z_lo + arb(2) * h
        z_c = (z_lo + z_hi) / arb(2)
        key = (pan["panel_ids"][kp], D, Z)
        if shared_cache is not None and key in shared_cache:
            sh = shared_cache[key]
            stats["hits"] += 1
        else:
            sh = OB.PanelShared(g["p_c"], g["m_c"], z_c, g["b"], ctxt)
            stats["misses"] += 1
            if shared_cache is not None:
                shared_cache[key] = sh
        N = H.panel_moments(z_lo, z_hi, z_c, g["e"], KMAX, h)
        av = P.absvecs_of(sh)
        for s in shifts:
            pd = OB.PanelDrift(sh, N) if s == 0 else PC.RawShiftDrift(sh, N, s, z_c, h)
            Rb = P.build_Rbig(pd)
            for (c, ss) in needed:
                if ss != s:
                    continue
                coef, ex, ez = OPT.contract_O9_memo(pd, cands[c], Rb, av, memo, c, kp)
                A = acc[(c, s)]
                for a in range(D + 1):
                    for bq in range(D + 1):
                        A[0][a][bq] += coef[a][bq]
                A[1] += ex
                A[2] += ez
                evals += 1
    stats["contract_evaluations"] = stats.get("contract_evaluations", 0) + evals
    return acc


def core(i, j, e, cands, *, cand_hashes, C_gate: Fr, shared_cache, mode):
    """Mirror of t2_final_certifier.certify_patch_final (same calls, same order) with compact export."""
    T.require_precision()
    if PC.RawShiftDrift is not ES.FixedRawShiftDrift or PC.L.softplus_local_enclosure is not BP.softplus_local_enclosure_p1:
        raise T.T1Refusal("T2-closed machinery not installed")
    g = PC.patch_geometry(i, j, e)
    pan = PC.panelisation(i, j, g)
    if not pan["P1_PASS"]:
        raise T.T1Refusal(f"P1 fails on ({i},{j})")
    pan["panel_ids"] = FC.canonical_panel_ids(i, j, pan["n_z"])
    ctxt = PC.context(g, pan["h"])
    exprs = {n: (EQ.image(n) if n in EQ.IMAGE_NODES else EQ.rhs(n)) for n in FC.NODES}
    needed = sorted({k for ex_ in exprs.values() for k in ex_.terms}, key=lambda k: (T.BASIS_ORDER.index(k[0]), k[1]))
    stats = {"hits": 0, "misses": 0}
    core_acc = contract_all_memo(g, pan, ctxt, cands, needed, shared_cache, stats)
    shifts = sorted({s for _, s in needed})
    sides = {"L": OPT.StripSideMemo(g, g["L_c"], "L", shifts), "U": OPT.StripSideMemo(g, g["U_c"], "U", shifts)}
    acc, end = {}, {}
    for key in needed:
        c, s = key
        pL, eL, _dL = sides["L"].contract(cands[c], s)
        pU, eU, _dU = sides["U"].contract(cands[c], s)
        acc[key] = ([[core_acc[key][0][a][b] - pL[a][b] - pU[a][b] for b in range(ES.DP)] for a in range(ES.DP)],
                    core_acc[key][1], core_acc[key][2])
        end[key] = eL + eU
    srcs = PC.source_tms(g, ctxt)
    pb = PC.PatchBasis(g, ctxt)
    alpha, beta = -g["p_c"], -g["m_c"]
    # x0 = (0,0) is EXACTLY the lower-left corner of the reset patch (0,0): p_c = m_c = H = b/128, so
    # alpha = beta = -H lies on the boundary of the Taylor-model box |alpha|,|beta| <= H (remainders valid there).
    x0_here = bool((i, j) == (0, 0) and (g["p_c"] - g["H"]).contains(arb(0)) and (g["m_c"] - g["H"]).contains(arb(0)))
    out = {}
    for n in FC.NODES:
        ex_ = exprs[n]
        if n in EQ.IMAGE_NODES:
            ch, dmid, _ = PC.assemble(ex_, g, acc, end, srcs)
            width = ch["trunc"] + ch["tail"] + ch["end"] + ch["int"]
            fin = all(ch[k].is_finite() for k in ("trunc", "tail", "end", "int"))
            rec = {"w": fup(width) if fin else None, "fin": fin}
            if x0_here and fin:
                v = arb(0)
                for a in range(ES.DP):
                    for b in range(ES.DP):
                        v += dmid[a][b] * ES.ipow(alpha, a) * ES.ipow(beta, b)
                v = v + arb(0, (ch["trunc"] + ch["tail"] + ch["end"]).upper())
                rec["x0"] = {"mid": _enc_exact(arb(v.mid())), "rad": _enc_exact(arb(v.rad()))}
        else:
            fh, ex_f = PC.candidate_on_patch(pb, cands[n])
            ch, dmid, _ = PC.assemble(ex_, g, acc, end, srcs, fh, ex_f)
            delta = ch["eq"] + ch["trunc"] + ch["tail"] + ch["end"] + ch["int"] + ch["round"]
            fin = all(v.is_finite() for v in ch.values()) and delta.is_finite()
            rec = {"d": fup(delta) if fin else None, "fin": fin,
                   "dom": max(ch, key=lambda k: PC.fr_upper(ch[k])) if fin else None}
            if EQ.local_gate(n):
                rec["ch"] = {k: fup(v) for k, v in ch.items()} if fin else None
                if mode == "mid" and fin:
                    gts = PC.gates(ch, C_gate)
                    r_end = C_gate * PC.fr_upper(ch["end"]) / Fr(1, 250)
                    rec["lg"] = {k: v["PASS"] for k, v in gts.items()}
                    rec["eg"] = {"ratio": fup(r_end), "PASS": r_end <= 1}
                    rec["lgb"] = PC.fr_upper(delta) <= Fr(1, 10) / C_gate     # LOCAL_GATE_BUDGET delta_max
        out[n] = rec
    geo = {"n_z": pan["n_z"], "panel_ids_sha256": hashlib.sha256(T.canonical(pan["panel_ids"])).hexdigest(),
           "strip_ids": ES.strip_ids(i, j), "P1": {"E_d": pan["p1"]["E_d"], "PASS": pan["P1_PASS"]},
           "strip_P1_PASS": all(v.P1_PASS for v in sides.values()),
           "contracts": len(needed), "contract_evaluations": stats["contract_evaluations"], "x0_patch": x0_here}
    return out, geo, stats
