#!/bin/sh
# Phase 1 stage profiles (frozen certifier) for cells 10 (low drift), 150 (mid), 368 (terminal): same 3 patches as 360,
# one process at a time, pinned to logical cpu 31 (SMT sibling of core 15) so the Phase-4 workers on 0-15 are not displaced.
PY=/home/ubuntu/work/ReBaseGuard/level4/.venv/bin/python
PP=/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_ps1_production_qualification/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_partition_successor/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_curvature_successor/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_t345_successor/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_t2_closure_successor/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_bint_p1_bound_successor/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_endpoint_strip_successor/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_t2_per_patch_successor/code:/home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_sr_o9_executor_t1_successor/code
for s in 10 150 368; do
  taskset -c 31 env -i HOME=/home/ubuntu PATH=/usr/bin:/bin LANG=C.UTF-8 OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 BLIS_NUM_THREADS=1 VECLIB_MAXIMUM_THREADS=1 PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=$PP $PY /home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_ps1_production_qualification/code/profile_patch.py $s /home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_ps1_production_qualification/evidence/profile "0,0;24,20;63,54" > /home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_ps1_production_qualification/evidence/profile/profile_s$s.log 2>&1
done
echo PROFILES_DONE > /home/ubuntu/work/ReBaseGuard-sr-o9-t1/level4/closure_proofs/p5y_k1_ps1_production_qualification/evidence/profile/done.txt
